Repository SomSomParty/SomSomParty_FE, pull requests merged in 2024-12, with the labels that each got.

#9 Feature/#2 축제 목록, 검색 api 연동
  src/components/CardList.jsx
  src/index.js
  src/pages/main/MainPage.jsx
  src/setupProxy.js
  src/styles/CardList.css
Labels: ✨ feature

#11 feat: 예약 api 연동
  src/App.js
  src/components/Reservation/Calendar.jsx
  src/components/Reservation/ReservationInfo.jsx
  src/pages/Reservation/Reservation.jsx
  src/pages/Reservation/ReservationCompleted.jsx
  src/pages/Reservation/WaitingRoom.jsx
Labels: ✨ feature

#16 Ci/#15 CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
Labels: 👷 ci

#21 Feature/#10
  package-lock.json
  package.json
  src/App.js
  src/api/chatApi.js
  src/api/chatJoinApi.js
  src/api/myChatListApi.js
  src/components/CardList.jsx
  src/pages/Chat/ChatInput.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatPage.css
  src/pages/Chat/ChatPage.jsx
  src/pages/Chat/ChatRoom.css
  src/pages/Chat/ChatRoom.jsx
  src/pages/Festival/FestivalDetail/FestivalButton.jsx
  src/pages/Festival/FestivalDetail/FestivalCard.jsx
  src/pages/Festival/FestivalDetail/FestivalDetail.css
  src/pages/Festival/FestivalDetail/FestivalImage.jsx
  src/pages/Festival/FestivalDetail/FestivalPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/my/MyPage.jsx
  src/setupProxy.js
  src/styles/my/MyPage.css
Labels: ✨ feature

#24 Refactor/ 내 예약 조회 로그인한 유저 정보로 변경
  src/pages/my/MyPage.jsx
Labels: :recycle: refactor

#26 Refactor/#25 로그인한 사용자 정보 받아오기
  package-lock.json
  package.json
  src/components/CardList.jsx
  src/components/reservation/ReservationInfo.jsx
  src/context/AuthContext.js
  src/pages/Festival/FestivalDetail/FestivalPage.jsx
  src/pages/auth/SignInPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/my/MyPage.jsx
  src/pages/reservation/Reservation.jsx
  src/pages/reservation/ReservationCompleted.jsx
  src/pages/reservation/WaitingRoom.jsx
Labels: ✨ feature, :recycle: refactor

#27 Refactor/ 채팅 로그인한 유저 정보로 변경
  src/api/chatJoinApi.js
  src/api/myChatListApi.js
  src/pages/Chat/ChatList.jsx
  src/pages/Chat/ChatPage.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Festival/FestivalDetail/FestivalPage.jsx
  src/pages/auth/SignInPage.jsx
Labels: :recycle: refactor
